//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTRO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public int IdHoaDon { get; set; }
        public Nullable<int> IdND { get; set; }
        public string TenND { get; set; }
        public string SDT { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<int> SoPhong { get; set; }
        public Nullable<float> TienDien { get; set; }
        public Nullable<float> TienNuoc { get; set; }
        public Nullable<float> TienPhong { get; set; }
        public Nullable<float> TongTien { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<float> TienNo { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PHONGTRO PHONGTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
    }
}
