//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTRO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public int IdHopDong { get; set; }
        public Nullable<int> IdND { get; set; }
        public string TenND { get; set; }
        public Nullable<int> IdPhong { get; set; }
        public Nullable<int> SoPhong { get; set; }
        public Nullable<float> TienPhong { get; set; }
        public Nullable<System.DateTime> NgayKi { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<float> TienCoc { get; set; }
        public Nullable<int> IdHoaDon { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PHONGTRO PHONGTRO { get; set; }
    }
}
