//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTRO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGTRO()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public int IDPhong { get; set; }
        public int SoPhong { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
        public string MoTa { get; set; }
        public Nullable<float> DienTich { get; set; }
        public Nullable<float> TienPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
    }
}
